apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-api
  namespace: library-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-api
  template:
    metadata:
      labels:
        app: symfony-api
    spec:
      containers:
        - name: symfony-api
          image: lms-api:latest       # <- use the exact name you loaded into Kind
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: "mysql"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "library_management_system"
            - name: DATABASE_USER
              value: "symfony"
            - name: DATABASE_PASSWORD
              value: "symfony"
            - name: DATABASE_URL
              value: "mysql://symfony:symfony@mysql:3306/library_management_system?serverVersion=9&charset=utf8mb4"
            - name: APP_ENV
              value: "dev"
            - name: APP_DEBUG
              value: "1"
            - name: RUN_MIGRATIONS
              value: "1"
            - name: JWT_SECRET_KEY
              value: "%kernel.project_dir%/config/jwt/private.pem"
            - name: JWT_PUBLIC_KEY
              value: "%kernel.project_dir%/config/jwt/public.pem"
            - name: JWT_PASSPHRASE
              value: "1d97e385cdff65c687b2299d6d19be58bbc2be50cae7850dc26501a062d6c249"

---
apiVersion: v1
kind: Service
metadata:
  name: symfony-api
  namespace: library-api
spec:
  type: NodePort
  selector:
    app: symfony-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
